# Generated by Django 5.0.7 on 2025-03-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('id', 'email')},
        ),
    ]
