# Generated by Django 4.2.4 on 2024-06-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_2fa_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
