# Generated by Django 5.0.7 on 2025-02-04 19:54

import Template.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='target_currency',
            field=Template.models.UppercaseCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='hoteldailybaserate',
            name='currency',
            field=Template.models.UppercaseCharField(max_length=5),
        ),
    ]
