# Generated by Django 5.0.6 on 2024-06-19 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('date_fetched', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange_rate',
            },
        ),
    ]
