# Generated by Django 5.0.7 on 2025-03-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_exchangerate_target_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldailybaserate',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mileagerate',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
