# Generated by Django 5.0.7 on 2025-03-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_hoteldailybaserate_code_mileagerate_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldailybaserate',
            old_name='code',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='mileagerate',
            old_name='code',
            new_name='value',
        ),
    ]
