# Generated by Django 5.0.7 on 2025-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_code_hoteldailybaserate_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileagerate',
            name='title',
        ),
        migrations.AlterField(
            model_name='mileagerate',
            name='value',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
