# Generated by Django 5.0.6 on 2024-06-05 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=20)),
                ('report_status', models.CharField(max_length=100)),
                ('report_date', models.DateField(null=True)),
                ('expense_type', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=1000)),
                ('payment_method', models.CharField(max_length=100)),
                ('report_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_currency', models.CharField(max_length=5)),
                ('report_submit_date', models.DateField(null=True)),
                ('integration_status', models.CharField(max_length=100)),
                ('integration_date', models.DateField(null=True)),
                ('error_message', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_type', models.CharField(max_length=50)),
                ('expense_date', models.DateField(null=True)),
                ('receipt_amount', models.CharField(max_length=200)),
                ('receipt_currency', models.CharField(max_length=200)),
                ('justification', models.CharField(max_length=2000)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('s3_path', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_destination', models.CharField(max_length=200, null=True)),
                ('employee_names', models.CharField(max_length=2000, null=True)),
                ('total_employees', models.IntegerField(null=True)),
                ('company_customer_name', models.CharField(max_length=2000, null=True)),
                ('business_topic', models.CharField(max_length=200, null=True)),
                ('total_attendees', models.IntegerField(null=True)),
                ('name_of_establishment', models.CharField(max_length=200, null=True)),
                ('hotel_name', models.CharField(max_length=200, null=True)),
                ('carrier', models.CharField(max_length=200, null=True)),
                ('distance', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.airline')),
                ('car_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.cartype')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city')),
                ('hotel_daily_base_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.hoteldailybaserate')),
                ('meal_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.mealcategory')),
                ('mileage_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.mileagerate')),
                ('relationship_to_pai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.relationshiptopai')),
                ('rental_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.rentalagency')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expensereport')),
            ],
            options={
                'db_table': 'expense_item',
                'managed': True,
            },
        ),
    ]
