# Generated by Django 4.2.4 on 2024-11-05 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.airline'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.cartype'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='hotel_daily_base_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.hoteldailybaserate'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='meal_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.mealcategory'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='mileage_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.mileagerate'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='relationship_to_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.relationshiptopai'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='rental_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.rentalagency'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expensereport'),
        ),
    ]
