# Generated by Django 5.0.6 on 2024-06-19 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensereport',
            name='error_message',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='report_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
