# Generated by Django 4.2.4 on 2024-06-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expensereport_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='error',
            field=models.BooleanField(default=True),
        ),
    ]
