# Generated by Django 5.0.7 on 2025-02-04 19:54

import Template.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='receipt_currency',
            field=Template.models.UppercaseCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='integration_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failure', 'Failure')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='report_currency',
            field=Template.models.UppercaseCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='report_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Open', max_length=20),
        ),
    ]
