# Generated by Django 5.0.7 on 2025-02-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenseitem_receipt_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseitem',
            old_name='company_customer_name',
            new_name='company_customer_name_title',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee1',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee10',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee2',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee3',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee4',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee5',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee6',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee7',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee8',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='attendee9',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name1',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name10',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name2',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name3',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name4',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name5',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name6',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name7',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name8',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='employee_name9',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
    ]
