# Generated by Django 5.0.7 on 2025-02-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_company_customer_name_expenseitem_company_customer_name_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
