# Generated by Django 5.0.7 on 2025-02-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenseitem_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
