# Generated by Django 5.0.7 on 2025-03-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expenseitem_exchange_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseitem',
            old_name='employee_name1',
            new_name='employee_names2',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name10',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name2',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name3',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name4',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name5',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name6',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name7',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name8',
        ),
        migrations.RemoveField(
            model_name='expenseitem',
            name='employee_name9',
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='employee_names',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
    ]
