# Generated by Django 5.0.7 on 2025-03-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_rename_employee_name1_expenseitem_employee_names2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='employee_names',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
