# Generated by Django 5.0.7 on 2025-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_expenseitem_employee_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='employee_names2',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
