# Generated by Django 5.0.7 on 2025-03-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expenseitem_employee_names2'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='iexp_report_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='iexp_report_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
