# Generated by Django 5.0.7 on 2025-03-16 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_expensereport_iexp_report_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='s3_path',
        ),
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s3_path', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expenses.expenseitem')),
            ],
            options={
                'db_table': 'expense_receipt',
            },
        ),
    ]
