# Generated by Django 5.0.7 on 2025-03-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_remove_expenseitem_s3_path_expensereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereceipt',
            name='s3_path',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
