name: Build and Deploy Django Serverless to Vercel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load All Secrets into Environment
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ secrets.ALL_SECRETS || toJSON(secrets) }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Load Fixture Data and Create Superuser
        run: |
          python manage.py check_and_load_fixture fixtures/initial_data.json

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token $VERCEL_TOKEN --prod --confirm
